const projects = [
 {id:'course-db',title:'数据库课程项目：校园二手书检索',kind:'课程作业',icon:'BookOpen',tags:['course','code'],owner:'pei',campus:'仙林校区',date:'2026-09-15',period:'6 周 · 09.16–10.28',hours:'每周 6 小时',roles:['前端开发','数据库设计'],summary:'一起完成课程项目的检索、数据建模和可视化界面。已有需求草案，希望每周做一次短同步。',goal:'完成可运行原型、测试报告与课程展示，重视代码和文档的共同维护。',requirement:'本课程选课同学，熟悉基础 SQL；分工不代替个人课程学习。',capacity:3,members:['pei']},
 {id:'research-reading',title:'多模态模型复现与论文阅读小组',kind:'自主科研',icon:'GraduationCap',tags:['research','ai'],owner:'lin',campus:'仙林校区',date:'2026-09-18',period:'8 周 · 本学期',hours:'每周 8 小时',roles:['模型复现','论文阅读'],summary:'从一篇公开论文开始，协作复现实验并整理实验记录，不涉及付费代做。',goal:'完成一个可复现实验仓库与一份结果分析报告。',requirement:'了解 Python 和基础深度学习；研究经验非必需。',capacity:3,members:['lin']},
 {id:'campus-data',title:'校园数据可视化工具',kind:'开发项目',icon:'Code2',tags:['code','innovation'],owner:'pei',campus:'鼓楼校区',date:'2026-09-21',period:'4 周 · 09.09–10.07',hours:'每周 4 小时',roles:['可视化设计','前端开发'],summary:'用公开示例数据制作课程时间与学习计划的可视化工具，已有数据处理伙伴。',goal:'完成桌面和手机都可浏览的交互原型。',requirement:'愿意共同迭代界面，时间可以协调。',capacity:3,members:['pei','chen']},
 {id:'study-economics',title:'计量经济学课程复习小组',kind:'课程学习',icon:'BookOpen',tags:['course','study'],owner:'li',campus:'鼓楼校区',date:'2026-09-16',period:'5 周 · 每周一次讨论',hours:'每周 3 小时',roles:['知识整理','习题讨论'],summary:'各自完成练习后讨论思路，轮流整理知识点，共同备考。',goal:'形成覆盖本学期重点内容的复习提纲。',requirement:'同课程同学；不共享未公开试题或代做作业。',capacity:4,members:['li']}
];
tags.push({id:'course',name:'课程协作',kind:'topic',aliases:['课设','课程项目','课程作业','课程学习']},{id:'research',name:'科研协作',kind:'topic',aliases:['科研','论文复现','科研项目']});
const initialUsers = {
 pei:{name:'裴同学',major:'计算机专业 · 大二',campus:'仙林校区',skills:['Python','数据处理','论文整理'],hours:'每周 6 小时',bio:'希望把课堂知识用到一个完整项目中。',verified:true},
 wang:{name:'小王',major:'数学专业 · 大三',campus:'仙林校区',skills:['数学建模','Python'],hours:'每周 8 小时',bio:'正在准备数学建模比赛。',verified:true},
 lin:{name:'小林',major:'计算机专业 · 大二',campus:'仙林校区',skills:['前端开发','Python'],hours:'每周 6 小时',bio:'想和伙伴完成课程与科研项目。',verified:true},
 li:{name:'小李',major:'外语专业 · 大二',campus:'鼓楼校区',skills:['英文写作','论文排版'],hours:'每周 6 小时',bio:'擅长文档与英文写作。',verified:true},
 chen:{name:'小陈',major:'计算机专业 · 大二',campus:'鼓楼校区',skills:['前端开发','数据处理'],hours:'每周 4 小时',bio:'关注校园应用。',verified:true},
 zhou:{name:'小周',major:'商学院 · 大二',campus:'仙林校区',skills:['用户调研','项目策划'],hours:'每周 5 小时',bio:'希望共同验证真实需求。',verified:true},
 fang:{name:'小方',major:'理学院 · 大二',campus:'仙林校区',skills:['羽毛球'],hours:'每周 2 小时',bio:'喜欢校内运动。',verified:true},
 zhao:{name:'小赵',major:'工学院 · 大一',campus:'仙林校区',skills:['篮球'],hours:'每周 2 小时',bio:'一起活动。',verified:true},
 xu:{name:'小许',major:'文学院 · 大二',campus:'鼓楼校区',skills:['跑步'],hours:'每周 2 小时',bio:'轻松运动。',verified:true},
 wu:{name:'小吴',major:'商学院 · 大三',campus:'仙林校区',skills:['学习自习'],hours:'每周 4 小时',bio:'按计划学习。',verified:true},
 tang:{name:'小唐',major:'艺术学院 · 大二',campus:'鼓楼校区',skills:['摄影'],hours:'每周 2 小时',bio:'记录校园。',verified:true},
 guest:{name:'新同学',major:'尚未填写资料',campus:'仙林校区',skills:[],hours:'尚未填写',bio:'',verified:false}
};
const nameId = name => Object.keys(initialUsers).find(id=>initialUsers[id].name===name)||'wang';
function seedCollaboration(){
 const result={posts:{},applications:[],messages:{},teams:{}};
 for(const t of topics)for(const [i,r] of t.teams.entries()){
  const id=t.id+'-team-'+i, owner=nameId(r.name),capacity=Number(r.slots.match(/\/\s*(\d+)/)?.[1]||3);
  result.posts[id]={id,title:r.title,owner,capacity,members:[owner],status:'open',roles:r.need.split(' / '),summary:r.summary,topicId:t.id,kind:'recruitment',campus:'仙林校区',hours:'每周 6–8 小时',date:t.date};
 }
 for(const p of projects)result.posts[p.id]={...p,status:'open',members:[...p.members]};
 for(const t of invitations){const owner=nameId(t.author);result.posts[t.id]={id:t.id,title:t.title,owner,capacity:t.total,members:[owner,...Object.keys(initialUsers).filter(id=>id!==owner&&id!=='guest'&&id!=='pei').slice(0,t.joined-1)],status:t.status,roles:['活动伙伴'],summary:t.summary,kind:'invitation',campus:t.campus,hours:t.time+'–'+t.end,date:t.date};}
 result.applications=[
  {id:'demo-math',postId:'math-2026-team-0',applicant:'pei',status:'chatting',confirmations:[],fields:{role:'论文协作',experience:'用 Python 完成过数据处理课程项目，也负责过报告整理。',hours:'每周 6 小时',reason:'希望完整参与一次数学建模比赛。'}},
  {id:'demo-course',postId:'course-db',applicant:'lin',status:'pending',confirmations:[],fields:{role:'前端开发',experience:'完成过 React 课程小项目，可以负责检索与可视化界面。',hours:'每周 6 小时',reason:'我们在同一门课，希望一起完成项目。'}},
  {id:'demo-li',postId:'math-2026-team-0',applicant:'li',status:'pending',confirmations:[],fields:{role:'英文写作',experience:'有课程英文报告和论文排版经历。',hours:'每周 6 小时',reason:'希望参与团队的英文写作与报告整理。'}}
 ];
 result.messages['demo-math']=[{from:'wang',text:'你好，看到你的项目经验了。我们可以先聊一下分工和每周时间。',time:'今天 10:20'},{from:'pei',text:'我可以负责数据整理，每周大概能投入 6 小时，也愿意参与报告。',time:'今天 10:23'}];
 result.teams['campus-data']={postId:'campus-data',plan:{roles:[{user:'pei',role:'数据处理与项目推进'},{user:'chen',role:'前端开发与图表'}],agenda:['确认原型范围与目标用户','核对数据字段与页面分工','确定第一次交付与下次同步时间'],risks:['仅使用公开或授权数据','确认每周可投入时间']},tasks:[{id:'seed-1',title:'整理公开示例数据与字段说明',owner:'pei',due:'2026-09-10',done:true},{id:'seed-2',title:'完成第一版图表与筛选布局',owner:'chen',due:'2026-09-12',done:false},{id:'seed-3',title:'一起检查手机端浏览效果',owner:'pei',due:'2026-09-13',done:false}]};
 return result;
}
let users=structuredClone(initialUsers),actor='pei',demoStore=seedCollaboration(),preferences={deadline:true,updates:true},readNotices=[];
const storageKey='campusmate-interaction-v2';
try{const saved=JSON.parse(sessionStorage.getItem(storageKey)||'null');if(saved?.version===2&&saved.store?.posts?.['course-db']){demoStore=saved.store;users=saved.users;actor=saved.actor;state.followed=new Set(saved.followed||[]);preferences=saved.preferences||preferences;readNotices=saved.readNotices||[];}}catch{}
function persistDemo(){try{sessionStorage.setItem(storageKey,JSON.stringify({version:2,store:demoStore,users,actor,followed:[...state.followed],preferences,readNotices}));}catch{}}
const user = id => users[id]||{name:'同学',major:'校园已认证',skills:[],verified:true};
const displayName = id => escapeHTML(user(id).name);
const avatar = id => `<span class="avatar">${escapeHTML(user(id).name.slice(0,1))}</span>`;
const statusName = status => ({pending:'待处理',chatting:'沟通中',joined:'已加入',rejected:'已拒绝',withdrawn:'已撤回',closed:'已结束',open:'招募中',full:'已满员'})[status]||status;
const statusBadge = status => `<span class="badge ${['joined','open'].includes(status)?'org':['pending','chatting'].includes(status)?'status':''}">${statusName(status)}</span>`;
const relevantApplications = () => demoStore.applications.filter(a=>a.applicant===actor||demoStore.posts[a.postId].owner===actor);
function appsFor(view){return relevantApplications().filter(a=>view==='received'?demoStore.posts[a.postId].owner===actor&&a.status==='pending':view==='sent'?a.applicant===actor:['chatting','joined'].includes(a.status));}
function renderGlobalNav(){
 const active=state.view==='messages'?'messages':['teams','team'].includes(state.view)?'teams':state.view==='profile'?'profile':'browse';
 const items=[['browse','发现','Compass'],['messages','消息','MessageSquare'],['teams','我的团队','Users'],['profile','我的','UserRound']];
 const content=items.map(([key,name,i])=>`<button type="button" data-nav="${key}" class="${active===key?'active':''}" aria-current="${active===key?'page':'false'}">${icon(i)}<span>${name}</span>${key==='messages'&&appsFor('received').length?`<span class="nav-counter">${appsFor('received').length}</span>`:''}</button>`).join('');
 $('global-nav').innerHTML=content;$('mobile-nav').innerHTML=content;$('user-name').textContent=user(actor).name;$('user-avatar').textContent=user(actor).name.slice(0,1);$('user-verification').textContent=user(actor).verified?'校园已认证':'待校园认证';
 $('demo-actor').innerHTML=Object.entries(users).map(([id,u])=>`<option value="${id}">${escapeHTML(u.name)}${u.verified?'':'（未认证）'}</option>`).join('');$('demo-actor').value=actor;$('demo-ai-failure').checked=state.aiFailure;
}
function goWorkspace(view){
 if(['messages','teams','team'].includes(view)&&!user(actor).verified){showCertification();return;}
 state.view=view;state.mobile=false;closeSuggestions();if($('modal').open)$('modal').close();render();window.scrollTo(0,0);
}
function syncRecruitments(){
 for(const t of topics)for(const [i,r] of t.teams.entries()){const p=demoStore.posts[t.id+'-team-'+i];r.slots=`${p.members.length} / ${p.capacity} 人`;}
 for(const t of invitations){const p=demoStore.posts[t.id];t.joined=p.members.length;t.status=p.status;}
}
function casualModeSwitch(){return `<div class="mode-switch" role="group" aria-label="自主组队类型"><button type="button" data-casual-mode="projects" class="${state.casualMode==='projects'?'active':''}" aria-pressed="${state.casualMode==='projects'}">项目协作</button><button type="button" data-casual-mode="daily" class="${state.casualMode==='daily'?'active':''}" aria-pressed="${state.casualMode==='daily'}">日常搭子</button></div>`;}
function matchingProjects(){const f=filter();return projects.filter(p=>f.tags.every(id=>p.tags.includes(id))&&(!f.campus||p.campus===f.campus)).sort((a,b)=>f.sort==='soon'?a.date.localeCompare(b.date):0);}
function renderProjectList(){
 const list=matchingProjects();$('result-count').textContent=`${list.length} 个项目 · 课程、科研与自主开发`;const f=filter();$('mobile-filter-label').textContent='筛选'+(f.tags.length||f.campus?` (${f.tags.length+Number(!!f.campus)})`:'');
 $('sort').innerHTML='<option value="recommended">推荐</option><option value="soon">截止时间</option>';$('sort').value=['soon','recommended'].includes(f.sort)?f.sort:'recommended';
 $('list-content').innerHTML=casualModeSwitch()+(list.length?`<div class="topic-grid">${list.map(p=>{const live=demoStore.posts[p.id];return `<article class="project-card"><div class="project-top">${icon(p.icon)}${p.kind}<span style="margin-left:auto">${statusBadge(live.status)}</span></div><button type="button" data-open="${p.id}" class="card-title">${p.title}</button><p class="summary">${p.summary}</p><div class="badges">${p.tags.map(badge).join('')}</div><div class="project-facts"><div><span>协作周期</span><strong>${p.period}</strong></div><div><span>投入时间</span><strong>${p.hours}</strong></div><div><span>需要角色</span><strong>${p.roles.join(' / ')}</strong></div><div><span>团队人数</span><strong>${live.members.length} / ${p.capacity} 人</strong></div></div><div class="card-foot"><span class="meta">${icon('UserRound')}${displayName(p.owner)} · 校园已认证</span><button class="text-button" type="button" data-open="${p.id}">查看项目${icon('ArrowRight')}</button></div></article>`;}).join('')}</div>`:`<div class="empty"><h3>暂无符合条件的项目</h3><p>试试减少筛选条件。</p><button class="button" type="button" data-action="clear">清空筛选</button></div>`);
}
function currentApplication(postId){return demoStore.applications.find(a=>a.postId===postId&&a.applicant===actor&&['pending','chatting','joined'].includes(a.status));}
function applicationAction(postId){
 const p=demoStore.posts[postId],a=currentApplication(postId);if(!p)return '';
 if(p.owner===actor)return `<button class="button primary" type="button" data-post-applications="${postId}">${icon('MessageSquare')}查看收到的申请</button>`;
 if(p.members.includes(actor))return demoStore.teams[postId]?`<button class="button primary" type="button" data-team-open="${postId}">${icon('Users')}进入我的团队</button>`:`<button class="button" type="button" disabled>已加入</button>`;
 if(a)return `<button class="button ${a.status==='chatting'?'primary':''}" type="button" data-app-open="${a.id}">${icon('MessageSquare')}${a.status==='pending'?'已申请 · 查看进度':a.status==='joined'?'查看组队结果':'继续沟通'}</button>`;
 if(p.status!=='open')return `<button type="button" class="button" disabled>${statusName(p.status)}</button>`;
 return `<button class="button primary" type="button" data-apply="${postId}">${icon('Users')}${user(actor).verified?'申请加入':'认证后申请'}</button>`;
}
function matchPanel(p){
 if(p.owner===actor)return `<div class="match-box"><h3>${icon('Sparkles')}招募条件</h3><p>需要 ${escapeHTML(p.roles.join(' / '))}，${escapeHTML(p.hours)}。收到申请后，可结合经验与时间安排进一步沟通。</p></div>`;
 if(state.aiFailure)return `<div class="error-band">AI 建议暂不可用。可先核对角色、投入时间和人数，仍能手动申请。</div>`;
 if(!user(actor).verified)return `<div class="match-box"><h3>${icon('Sparkles')}匹配建议</h3><p>完成校园认证并补充技能后，可查看与你有关的匹配建议。</p></div>`;
 const skills=user(actor).skills;let reasons=[],warning='建议先确认每周投入时间和协作目标。',score=76;
 if(p.kind==='invitation'){reasons=[`活动位于${p.campus}`,`目前还缺 ${Math.max(0,p.capacity-p.members.length)} 人`];score=80;warning='请自行确认活动时间、运动强度与场地安排。';}
 else if(p.id.includes('math')){reasons=[skills.includes('Python')?'你的 Python 经验可用于数据处理':'你的文档与写作经验可以补充团队表达',`团队需要 ${p.roles.join(' / ')}`];warning='你的经验尚不能证明已满足全部角色要求，建议先交流作品与时间。';}
 else{reasons=[`你的技能：${skills.join('、')||'尚未补充'}`,`项目需要 ${p.roles.join(' / ')}`];warning=p.kind==='课程作业'?'请先确认同课程资格和个人作业要求。':'建议先对齐交付目标、可投入时间与协作方式。';}
 return `<div class="match-box"><h3>${icon('Sparkles')}匹配建议 <small>示例结果，非真实模型</small></h3><p><span class="match-score">${score}</span> / 100 · 待双方进一步确认</p><ul>${reasons.map(r=>`<li>${escapeHTML(r)}</li>`).join('')}</ul><p class="warning">${escapeHTML(warning)}</p></div>`;
}
function renderProjectDetail(p){
 const live=demoStore.posts[p.id];$('detail').innerHTML=`<div class="breadcrumb"><button class="text-button" type="button" data-action="back">${icon('ArrowLeft')}返回项目协作</button>${icon('ChevronRight')}自主项目</div><div class="detail-layout"><section><div class="project-top">${icon(p.icon)}${p.kind} · 学生自主发起</div><div class="detail-heading"><h1>${p.title}</h1><div class="badges">${p.tags.map(badge).join('')}</div><p>${p.summary}</p></div><div class="status-strip"><span class="status-label">项目</span><span class="badge">筹备中</span><span class="status-label">招募</span>${statusBadge(live.status)}<span class="status-label">我的状态</span><span>${live.owner===actor?'发起人':live.members.includes(actor)?'团队成员':currentApplication(p.id)?statusName(currentApplication(p.id).status):'尚未申请'}</span></div><section class="article-section"><h3>目标与交付</h3><p>${p.goal}</p><div class="fact-grid"><div class="fact"><small>项目周期</small><strong>${p.period}</strong></div><div class="fact"><small>每周投入</small><strong>${p.hours}</strong></div><div class="fact"><small>需要角色</small><strong>${p.roles.join(' / ')}</strong></div><div class="fact"><small>招募截止</small><strong>${p.date}</strong></div></div></section><section class="article-section"><h3>协作要求</h3><p>${p.requirement}</p></section>${matchPanel(live)}<section class="article-section"><h3>相关项目</h3>${projects.filter(item=>item.id!==p.id&&item.tags.some(tag=>p.tags.includes(tag))).slice(0,2).map(item=>`<div class="profile-row"><div><h3>${item.title}</h3><p>${item.kind} · ${item.hours}</p></div><button type="button" class="button" data-open="${item.id}">查看${icon('ChevronRight')}</button></div>`).join('')||'<p>暂时没有相似项目。</p>'}</section></section><aside class="detail-side"><section class="side-section"><h3>发起同学</h3><div class="member-row">${avatar(p.owner)}<div><strong>${displayName(p.owner)}</strong><small>${escapeHTML(user(p.owner).major)}</small></div></div><span class="badge org">校园已认证</span></section><section class="side-section"><h3>组队进度</h3><div class="side-stat">${icon('Users')}<strong>${live.members.length} / ${p.capacity}</strong>人已加入</div>${applicationAction(p.id)}<p>双方确认后加入，未满员时继续招募。</p></section><section class="side-section"><h3>协作范围</h3><p>${p.campus} · ${p.requirement}</p></section></aside></div>`;
}
function openRecruitment(id){const p=demoStore.posts[id];showModal(p.title,`<p>${escapeHTML(p.summary)}</p><div class="status-strip">${statusBadge(p.status)}<span>${p.members.length}/${p.capacity} 人</span><span>${displayName(p.owner)} · 校园已认证</span></div><div class="fact-grid"><div class="fact"><small>所需角色</small><strong>${escapeHTML(p.roles.join(' / '))}</strong></div><div class="fact"><small>每周投入</small><strong>${escapeHTML(p.hours)}</strong></div></div>${matchPanel(p)}${applicationAction(id)}`);}
function openApplyForm(id){
 if(!user(actor).verified){showCertification();return;}const p=demoStore.posts[id];
 showModal('申请加入',`<form id="application-form" data-post-id="${id}" class="application-form"><h3>${escapeHTML(p.title)}</h3><div class="form-grid"><label class="field">希望承担的角色<select name="role" required>${p.roles.map(r=>`<option>${escapeHTML(r)}</option>`).join('')}</select></label><label class="field">可投入时间<input name="hours" value="${escapeHTML(user(actor).hours)}" maxlength="80" required></label><label class="field full">相关经验<textarea name="experience" maxlength="400" required placeholder="介绍相关课程、项目或活动经验"></textarea></label><label class="field full">加入原因<textarea name="reason" maxlength="300" required placeholder="你希望与队友共同完成什么"></textarea></label><label class="field full">想提前确认的问题（选填）<input name="question" maxlength="180" placeholder="例如每周讨论时间"></label></div><p class="form-error" id="application-error" role="alert"></p><div class="form-actions"><button type="button" class="button" data-close-dialog>取消</button><button type="submit" class="button primary">提交申请${icon('ArrowRight')}</button></div></form>`);
}
function dispatchCollaboration(action){demoStore=Collaboration.reduce(demoStore,{...action,actor});persistDemo();syncRecruitments();}
function showCertification(){showModal('校园认证',`<div class="progress-track"><span class="complete">${icon('CheckCircle2')}账户资料</span>${icon('ChevronRight')}<span>校园邮箱验证</span>${icon('ChevronRight')}<span>获得申请权限</span></div><p>当前身份尚未完成校园认证。公开活动仍可浏览。</p><label class="field">校园邮箱<input type="email" placeholder="你的校园邮箱" disabled></label><div class="form-actions"><button type="button" class="button" disabled>验证邮件服务尚未接入</button></div>`);}
function renderWorkspace(){if(state.view==='messages')renderMessages();else if(state.view==='teams')renderTeamList();else if(state.view==='team')renderTeamWorkspace();else renderProfile();}
function renderMessages(){
 const tabs=[['received','收到申请'],['sent','我的申请'],['chat','临时沟通'],['notifications','通知']];
 let content=`<div class="workspace-head"><div><h1>消息与申请</h1><p>查看申请进度，与队友保持联系</p></div><span class="muted small">${displayName(actor)} · 校园已认证</span></div><div class="workspace-tabs">${tabs.map(([key,label])=>`<button type="button" data-inbox="${key}" class="${state.inbox===key?'active':''}">${label}${key!=='notifications'&&appsFor(key).length?`<span class="nav-counter">${appsFor(key).length}</span>`:''}</button>`).join('')}</div>`;
 if(state.inbox==='notifications'){content+=renderNotifications();$('workspace').innerHTML=content;return;}
 const list=appsFor(state.inbox),selected=list.find(a=>a.id===state.selectedApp)||list[0];
 content+=`<div class="message-shell ${state.selectedApp?'show-thread':''}"><aside class="thread-list" aria-label="申请会话列表">${list.map(a=>{const p=demoStore.posts[a.postId],other=a.applicant===actor?p.owner:a.applicant,last=demoStore.messages[a.id]?.at(-1);return `<button type="button" class="thread-button ${selected?.id===a.id?'active':''}" data-thread="${a.id}"><span class="thread-title">${avatar(other)}<strong>${displayName(other)}</strong>${statusBadge(a.status)}</span><p>${escapeHTML(p.title)}</p><small>${last?escapeHTML(last.text):escapeHTML(a.fields?.role||'待进一步沟通')}</small></button>`;}).join('')||'<div class="tab-empty">暂无这类申请</div>'}</aside><section class="thread-content">${selected?renderThread(selected):'<div class="tab-empty">新的申请和沟通会显示在这里。</div>'}</section></div>`;
 $('workspace').innerHTML=content;
}
function renderThread(a){
 const p=demoStore.posts[a.postId],other=a.applicant===actor?p.owner:a.applicant,isOwner=p.owner===actor;
 let html=`<button type="button" class="text-button thread-back" data-thread-back>${icon('ArrowLeft')}返回列表</button><div class="thread-heading"><div><h2>${displayName(other)}</h2><p>${escapeHTML(p.title)}</p></div>${statusBadge(a.status)}</div><div class="progress-track"><span class="complete">${icon('CheckCircle2')}申请已提交</span>${icon('ChevronRight')}<span class="${['chatting','joined'].includes(a.status)?'complete':''}">${icon('MessageSquare')}临时沟通</span>${icon('ChevronRight')}<span class="${a.status==='joined'?'complete':''}">${icon('Users')}双方确认加入</span></div>`;
 if(a.status==='pending'){
  html+=`<dl class="application-facts"><dt>希望承担</dt><dd>${escapeHTML(a.fields.role)}</dd><dt>相关经验</dt><dd>${escapeHTML(a.fields.experience)}</dd><dt>可投入时间</dt><dd>${escapeHTML(a.fields.hours)}</dd><dt>加入原因</dt><dd>${escapeHTML(a.fields.reason)}</dd>${a.fields.question?`<dt>希望确认</dt><dd>${escapeHTML(a.fields.question)}</dd>`:''}</dl><p class="inline-note">接受申请后先进入临时沟通，双方确认前不交换联系方式。</p><div class="form-actions">${isOwner?`<button class="button" type="button" data-app-action="reject" data-id="${a.id}">暂不接受</button><button class="button primary" type="button" data-app-action="accept" data-id="${a.id}">接受并沟通${icon('ArrowRight')}</button>`:`<button class="button" type="button" data-app-action="withdraw" data-id="${a.id}">撤回申请</button>`}</div>`;
 }else if(['chatting','joined'].includes(a.status)){
  const joined=a.status==='joined';
  html+=`<div class="chat-safety">${icon(joined?'ShieldCheck':'LockKeyhole')}${joined?'已加入同一团队，联系方式可在团队内查看。':'双方确认前，联系方式保持隐藏。'}</div><div class="chat-feed" id="chat-feed">${(demoStore.messages[a.id]||[]).map(m=>`<div class="chat-line ${m.from===actor?'mine':''}">${avatar(m.from)}<div><div class="chat-bubble">${escapeHTML(m.text)}</div><div class="chat-meta">${displayName(m.from)} · ${escapeHTML(m.time||'刚刚')}</div></div></div>`).join('')||'<div class="tab-empty">申请已接受，可以先交流角色和时间安排。</div>'}</div><form class="chat-composer" id="chat-form" data-app-id="${a.id}"><textarea name="message" maxlength="800" aria-label="聊天消息" placeholder="输入消息" required></textarea><button class="icon-button" type="submit" aria-label="发送消息" title="发送消息">${icon('Send')}</button></form>`;
  if(joined)html+=`<div class="confirm-panel"><div><strong class="small">已加入团队 · ${p.members.length}/${p.capacity} 人</strong><p class="muted small">${p.members.length<p.capacity?'团队仍有名额，可继续招募。':'本次招募已满员。'}</p></div><button class="button primary" type="button" data-team-open="${p.id}">进入团队${icon('ArrowRight')}</button></div>`;
  else html+=`<div class="confirm-panel"><div class="confirm-state"><span class="${a.confirmations.includes(actor)?'confirmed':''}">${icon(a.confirmations.includes(actor)?'CheckCircle2':'Clock')}你${a.confirmations.includes(actor)?'已确认':'待确认'}</span><span class="${a.confirmations.includes(other)?'confirmed':''}">${icon(a.confirmations.includes(other)?'CheckCircle2':'Clock')}对方${a.confirmations.includes(other)?'已确认':'待确认'}</span></div><div class="confirm-buttons"><button class="button" type="button" data-app-action="close" data-id="${a.id}">结束沟通</button><button class="button primary" type="button" data-app-action="confirm" data-id="${a.id}" ${a.confirmations.includes(actor)?'disabled':''}>${a.confirmations.includes(actor)?'等待对方确认':isOwner?'确认接纳':'确认加入'}</button></div></div>`;
 }else html+=`<div class="tab-empty">${statusName(a.status)}。这条申请不会再产生新的成员确认。</div><button class="button" type="button" data-nav="browse">继续发现${icon('ArrowRight')}</button>`;
 return html;
}
function renderNotifications(){
 const notices=[];for(const t of topics.filter(t=>state.followed.has(t.id))){if(preferences.deadline)notices.push({id:t.id+'-deadline',title:t.title+' · 截止提醒',body:t.dateLabel+'，组队与主办方正式报名分别进行。',topic:t.id});if(preferences.updates)notices.push({id:t.id+'-update',title:t.title+' · 资料记录',body:'关注的话题可查看来源记录、资料与核验时间。',topic:t.id});}
 return `<div style="padding:10px 0 38px">${notices.map(n=>`<article class="notice-row"><div class="notice-icon">${icon('Bell')}</div><div><h3>${n.title}</h3><p>${n.body}</p><small>${readNotices.includes(n.id)?'已读':'未读'} · 示例通知</small></div><button class="button" type="button" data-notice="${n.id}" data-notice-topic="${n.topic}">查看话题${icon('ChevronRight')}</button></article>`).join('')||`<div class="tab-empty">暂无关注提醒。关注话题后，可在这里查看截止与资料更新消息。</div>`}</div>`;
}
function memberTeams(){return Object.values(demoStore.teams).filter(t=>demoStore.posts[t.postId].members.includes(actor));}
function renderTeamList(){
 const list=memberTeams();$('workspace').innerHTML=`<div class="workspace-head"><div><h1>我的团队</h1><p>${list.length} 个正在协作的团队</p></div><button class="button" type="button" data-nav="browse">寻找更多项目${icon('ArrowRight')}</button></div><div class="team-grid">${list.map(t=>{const p=demoStore.posts[t.postId],done=t.tasks.filter(task=>task.done).length;return `<article class="team-card"><div class="project-top">${icon(p.kind==='invitation'?'CircleDot':'FolderKanban')}${p.kind==='invitation'?'活动小组':p.topicId?'参赛团队':'项目团队'}<span style="margin-left:auto">${statusBadge(p.status)}</span></div><h3>${escapeHTML(p.title)}</h3><div class="member-stack">${p.members.map(avatar).join('')}</div><p>${p.members.length}/${p.capacity} 人 · ${p.members.length<p.capacity?'仍有 '+(p.capacity-p.members.length)+' 个名额':'人员已齐'}</p><div class="team-progress"><span style="width:${t.tasks.length?done/t.tasks.length*100:0}%"></span></div><p style="margin-top:8px">${done}/${t.tasks.length} 项任务已完成</p><button class="button" type="button" data-team-open="${p.id}">进入团队${icon('ArrowRight')}</button></article>`;}).join('')||`<div class="empty"><h3>还没有加入团队</h3><p>与招募者双方确认后，团队会显示在这里。</p><button class="button" type="button" data-nav="messages">查看我的申请</button></div>`}</div>`;
}
let planningFor=null;
function renderTeamWorkspace(){
 const team=demoStore.teams[state.teamId],p=demoStore.posts[state.teamId];
 if(!team||!p?.members.includes(actor)){$('workspace').innerHTML=`<div class="empty"><h3>仅团队成员可查看</h3><p>当前身份尚未加入这个团队。</p><button class="button" type="button" data-nav="teams">返回我的团队</button></div>`;return;}
 const tabs=[['overview','协作概览'],['tasks','任务清单'],['meeting','首次会议']];
 let html=`<div class="breadcrumb"><button class="text-button" type="button" data-nav="teams">${icon('ArrowLeft')}我的团队</button>${icon('ChevronRight')}团队空间</div><div class="workspace-head" style="padding-top:0"><div><h1>${escapeHTML(p.title)}</h1><p>${p.members.length}/${p.capacity} 人 · ${p.members.length<p.capacity?'继续招募中':'人员已齐'} · ${p.topicId?'官方报名需另行完成':'按协作目标推进'}</p></div>${statusBadge(p.status)}</div><div class="workspace-tabs">${tabs.map(([key,name])=>`<button type="button" data-team-tab="${key}" class="${state.teamTab===key?'active':''}">${name}${key==='tasks'?`<span class="nav-counter">${team.tasks.length}</span>`:''}</button>`).join('')}</div><div class="team-main-layout"><section>`;
 if(state.teamTab==='tasks')html+=taskList(team,p);
 else if(state.teamTab==='meeting')html+=`<section class="team-section"><h3>第一次会议</h3><p>建议用 30 分钟对齐目标、角色和近期交付。</p>${team.plan?team.plan.agenda.map((item,i)=>`<div class="agenda-row"><span>${i*10}–${(i+1)*10} 分钟</span><p>${escapeHTML(item)}</p></div>`).join(''):planPanel(team,p)}</section>`;
 else html+=`<section class="team-section"><h3>下一步</h3><p>${p.members.length<p.capacity?'已有成员可以先开始协作，同时继续寻找剩余伙伴。':'人员已齐，先确认角色分工和第一次会议安排。'}</p></section>${planPanel(team,p)}<section class="team-section"><h3>近期任务</h3>${team.tasks.length?taskList(team,p,true):'<p>暂无任务，可以手动添加，或查看 AI 分工建议。</p>'}</section>`;
 html+=`</section><aside class="team-sidebar"><h3>团队成员 · ${p.members.length}/${p.capacity}</h3>${p.members.map(id=>`<div class="member-row">${avatar(id)}<div><strong>${displayName(id)}</strong><small>${escapeHTML(user(id).skills.join('、'))}</small></div>${p.owner===id?'<span class="badge org">发起人</span>':''}</div>`).join('')}<section class="side-section"><h3>联系方式</h3>${Collaboration.canViewContact(demoStore,p.id,actor)?`<div class="source-box"><span>${icon('ShieldCheck')}成员确认后可见</span></div>${p.members.filter(id=>id!==actor).map(id=>`<div class="readonly-contact"><strong>${displayName(id)}</strong><br>站内联系：${escapeHTML('demo_'+id)}<br><span class="small">虚构账号，仅用于草图</span></div>`).join('')}`:`<p>尚未解锁</p>`}</section><section class="side-section"><h3>人数与招募</h3><p>${p.members.length} 人已经确认，${Math.max(0,p.capacity-p.members.length)} 个剩余名额。</p>${p.topicId?`<button type="button" class="button" data-open="${p.topicId}" data-subtab="teams">查看关联话题</button>`:p.kind==='invitation'?`<button type="button" class="button" data-open="${p.id}">查看本次邀约</button>`:`<button type="button" class="button" data-open="${p.id}">查看项目招募</button>`}</section></aside></div>`;
 $('workspace').innerHTML=html;
}
function planPanel(team,p){
 if(planningFor===p.id)return `<div class="loading-line" role="status">${icon('Sparkles')}正在整理成员能力与分工建议…</div>`;
 if(team.plan)return `<section class="team-section"><h3>${icon('Sparkles')}分工建议 <span class="badge">AI 示例，可调整</span></h3>${team.plan.roles.map(r=>`<div class="profile-row"><div><h3>${displayName(r.user)}</h3><p>${escapeHTML(r.role)}</p></div><button class="icon-button" type="button" data-edit-role="${r.user}" title="修改${user(r.user).name}的分工" aria-label="修改${user(r.user).name}的分工">${icon('Pencil')}</button></div>`).join('')}<div class="inline-note">${team.plan.risks.map(escapeHTML).join('；')}。</div></section>`;
 return `<section class="team-section"><div class="match-box"><h3>${icon('Sparkles')}把团队目标变成第一步 <small>AI 示例</small></h3><p>根据已确认成员的技能，整理分工、首次会议与近期任务。</p><button class="button primary" type="button" data-generate-plan="${p.id}">生成协作建议${icon('ArrowRight')}</button></div>${state.planError===p.id?'<div class="error-band" role="alert">AI 服务暂不可用，团队已成功建立。可以重试或手动添加任务。</div>':''}<button class="text-button small" type="button" data-new-task>${icon('Plus')}手动添加任务</button></section>`;
}
function taskList(team,p,compact=false){const tasks=compact?team.tasks.slice(0,3):team.tasks;return `<div class="task-toolbar"><span class="muted small">${team.tasks.filter(t=>t.done).length}/${team.tasks.length} 已完成</span><button class="button" type="button" data-new-task>${icon('Plus')}添加任务</button></div><div class="task-list">${tasks.map(t=>`<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-task-check="${t.id}" ${t.done?'checked':''} aria-label="完成任务：${escapeHTML(t.title)}"><span class="task-name">${escapeHTML(t.title)}</span><span class="task-date">${escapeHTML(t.due)}</span><span class="task-owner">${displayName(t.owner)}</span><button class="icon-button task-edit" type="button" data-edit-task="${t.id}" title="编辑任务" aria-label="编辑任务：${escapeHTML(t.title)}">${icon('Pencil')}</button></div>`).join('')||'<div class="tab-empty">暂无任务</div>'}</div>`;}
function openTaskForm(taskId){const team=demoStore.teams[state.teamId],p=demoStore.posts[state.teamId];if(!p.members.includes(actor))return;const task=team.tasks.find(t=>t.id===taskId);showModal(task?'编辑任务':'添加任务',`<form id="task-form" data-task-id="${taskId||''}"><div class="form-grid"><label class="field full">任务标题<input name="title" required maxlength="100" value="${escapeHTML(task?.title||'')}" placeholder="这一步要完成什么"></label><label class="field">负责人<select name="owner">${p.members.map(id=>`<option value="${id}" ${task?.owner===id?'selected':''}>${displayName(id)}</option>`).join('')}</select></label><label class="field">截止日期<input name="due" type="date" required value="${task?.due||'2026-09-12'}"></label></div><div class="form-actions"><button class="button" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">保存任务</button></div></form>`);}
function renderProfile(){
 const u=user(actor),posts=Object.values(demoStore.posts).filter(p=>p.owner===actor),applications=demoStore.applications.filter(a=>a.applicant===actor);const tabs=[['overview','我的动态'],['saved','我的关注'],['settings','偏好设置']];
 let html=`<div class="workspace-head"><div><h1>我的</h1><p>管理资料、关注与参与记录</p></div></div><div class="profile-grid"><aside class="profile-summary">${avatar(actor)}<h2>${displayName(actor)}</h2><p>${escapeHTML(u.major)} · ${escapeHTML(u.campus)}</p><div class="badges"><span class="badge ${u.verified?'org':'status'}">${u.verified?'校园已认证':'待校园认证'}</span>${u.skills.map(s=>`<span class="badge topic">${escapeHTML(s)}</span>`).join('')}</div><p>${escapeHTML(u.bio||'尚未填写个人介绍')}</p><button class="button" type="button" data-edit-profile>${icon('Pencil')}编辑资料</button><button class="button" type="button" data-certification>${icon('BadgeCheck')}认证管理</button><div class="profile-stats"><span><strong>${posts.length}</strong>我的招募</span><span><strong>${applications.length}</strong>我的申请</span><span><strong>${memberTeams().length}</strong>我的团队</span></div></aside><section><div class="workspace-tabs">${tabs.map(([key,name])=>`<button class="${state.profileTab===key?'active':''}" type="button" data-profile-tab="${key}">${name}</button>`).join('')}</div>`;
 if(state.profileTab==='saved')html+=topics.filter(t=>state.followed.has(t.id)).map(t=>`<div class="profile-row"><div><h3>${t.title}</h3><p>${t.dateLabel} · ${t.source}</p></div><button class="button" type="button" data-open="${t.id}">查看话题</button><button class="icon-button" type="button" data-unsave="${t.id}" title="取消关注" aria-label="取消关注${t.title}">${icon('X')}</button></div>`).join('')||'<div class="tab-empty">还没有关注话题</div>';
 else if(state.profileTab==='settings')html+=`<label class="preference"><span>关注话题的截止提醒</span><input type="checkbox" data-preference="deadline" ${preferences.deadline?'checked':''}></label><label class="preference"><span>关注话题的资料更新提醒</span><input type="checkbox" data-preference="updates" ${preferences.updates?'checked':''}></label><div class="side-section"><h3>公开资料</h3><p class="settings-note">公开展示昵称、专业年级与技能；联系方式仅在确认加入的团队中可见。</p></div>`;
 else html+=`<section class="team-section" style="padding-top:20px"><h3>我的招募</h3>${posts.map(p=>`<div class="profile-row"><div><h3>${escapeHTML(p.title)}</h3><p>${p.members.length}/${p.capacity} 人 · ${p.kind==='invitation'?'日常邀约':p.topicId?'赛事招募':'自主项目'}</p></div>${statusBadge(p.status)}<button class="button" type="button" data-post-applications="${p.id}">查看申请</button></div>`).join('')||'<p>暂无已发布招募。</p>'}</section><section class="team-section"><h3>我的申请</h3>${applications.map(a=>`<div class="profile-row"><div><h3>${escapeHTML(demoStore.posts[a.postId].title)}</h3><p>${escapeHTML(a.fields?.role||'活动伙伴')}</p></div>${statusBadge(a.status)}<button class="button" type="button" data-app-open="${a.id}">查看进度</button></div>`).join('')||'<p>暂无申请记录。</p>'}</section>`;
 $('workspace').innerHTML=html+'</section></div>';
}
function openProfileForm(){const u=user(actor);const skillOptions=['Python','数据处理','前端开发','数学建模','英文写作','论文整理','论文排版','用户调研','项目策划','羽毛球'];showModal('编辑资料',`<form id="profile-form"><div class="form-grid"><label class="field">昵称<input name="name" maxlength="12" required value="${escapeHTML(u.name)}"></label><label class="field">专业与年级<input name="major" maxlength="40" required value="${escapeHTML(u.major)}"></label><label class="field">所在校区<select name="campus">${['仙林校区','鼓楼校区'].map(c=>`<option ${c===u.campus?'selected':''}>${c}</option>`).join('')}</select></label><label class="field">可投入时间<input name="hours" maxlength="40" required value="${escapeHTML(u.hours)}"></label><div class="field full"><span>技能</span><div class="skill-options">${skillOptions.map(s=>`<label class="radio-row"><input type="checkbox" name="skills" value="${s}" ${u.skills.includes(s)?'checked':''}>${s}</label>`).join('')}</div></div><label class="field full">个人介绍<textarea name="bio" maxlength="180">${escapeHTML(u.bio)}</textarea></label></div><div class="form-actions"><button class="button" type="button" data-close-dialog>取消</button><button class="button primary" type="submit">保存资料</button></div></form>`);}
document.addEventListener('click',event=>{
 const b=event.target.closest('button');if(!b)return;
 try{
 if(b.dataset.nav){state.selectedApp=null;goWorkspace(b.dataset.nav);return;}
 if(b.dataset.casualMode){state.casualMode=b.dataset.casualMode;state.filters.casual=freshFilter();state.mobile=false;render();return;}
 if(b.dataset.apply){openApplyForm(b.dataset.apply);return;}
 if(b.hasAttribute('data-close-dialog')){$('modal').close();return;}
 if(b.dataset.inbox){state.inbox=b.dataset.inbox;state.selectedApp=null;render();return;}
 if(b.dataset.thread){state.selectedApp=b.dataset.thread;render();return;}
 if(b.hasAttribute('data-thread-back')){state.selectedApp=null;render();return;}
 if(b.dataset.appOpen){const a=demoStore.applications.find(a=>a.id===b.dataset.appOpen);state.inbox=['chatting','joined'].includes(a.status)?'chat':a.applicant===actor?'sent':'received';state.selectedApp=a.id;goWorkspace('messages');return;}
 if(b.dataset.postApplications){const postId=b.dataset.postApplications;const a=demoStore.applications.find(a=>a.postId===postId&&a.status==='pending')||demoStore.applications.find(a=>a.postId===postId&&['chatting','joined'].includes(a.status));if(!a){showModal('暂无进行中的申请',`<p>${escapeHTML(demoStore.posts[postId].title)}</p><p>这个招募目前没有待处理申请或进行中的沟通。</p><button type="button" class="button" data-nav="messages">查看全部申请</button>`);return;}state.inbox=a.status==='pending'?'received':'chat';state.selectedApp=a.id;goWorkspace('messages');return;}
 if(b.dataset.appAction){dispatchCollaboration({type:b.dataset.appAction,appId:b.dataset.id});state.selectedApp=b.dataset.id;if(b.dataset.appAction==='accept')state.inbox='chat';render();toast(({accept:'已接受，可以开始沟通',reject:'已拒绝申请',confirm:'确认状态已更新',withdraw:'申请已撤回',close:'沟通已结束'})[b.dataset.appAction]);return;}
 if(b.dataset.teamOpen){state.teamId=b.dataset.teamOpen;state.teamTab='overview';goWorkspace('team');return;}
 if(b.dataset.teamTab){state.teamTab=b.dataset.teamTab;render();return;}
 if(b.dataset.profileTab){state.profileTab=b.dataset.profileTab;render();return;}
 if(b.hasAttribute('data-edit-profile')){openProfileForm();return;}
 if(b.hasAttribute('data-certification')){if(user(actor).verified)showModal('认证管理',`<p>${displayName(actor)} · 校园已认证</p><div class="source-box"><span>${icon('BadgeCheck')}示例校园邮箱认证</span><span>${icon('ShieldCheck')}仅保存认证结果，不展示证明材料</span></div><p class="inline-note">组织发布权限需另行申请，本人的校园认证不代表组织授权。</p>`);else showCertification();return;}
 if(b.dataset.unsave){state.followed.delete(b.dataset.unsave);render();return;}
 if(b.dataset.notice){if(!readNotices.includes(b.dataset.notice))readNotices.push(b.dataset.notice);openDetail(b.dataset.noticeTopic);return;}
 if(b.hasAttribute('data-new-task')){openTaskForm();return;}
 if(b.dataset.editTask){openTaskForm(b.dataset.editTask);return;}
 if(b.dataset.editRole){const team=demoStore.teams[state.teamId],r=team.plan.roles.find(r=>r.user===b.dataset.editRole);showModal('修改分工',`<form id="role-form" data-user-id="${r.user}"><label class="field">${displayName(r.user)}的分工<input name="role" maxlength="100" required value="${escapeHTML(r.role)}"></label><div class="form-actions"><button class="button primary" type="submit">保存分工</button></div></form>`);return;}
 if(b.dataset.generatePlan){const id=b.dataset.generatePlan;if(planningFor)return;planningFor=id;state.planError=null;render();setTimeout(()=>{planningFor=null;if(state.aiFailure){state.planError=id;render();return;}const team=demoStore.teams[id],p=demoStore.posts[id];team.plan={roles:p.members.map((member,i)=>({user:member,role:i===0?'目标协调、进度与核心方案':user(member).skills.slice(0,2).join('与')+'，协作完成交付'})),agenda:['确认项目目标、边界和报名要求','根据成员技能核对分工与时间','确定首个交付与后续同步安排'],risks:['AI 建议需由成员确认','队伍人数变化后重新核对分工与时间','联系方式只在已加入成员间共享']};if(!team.tasks.length)team.tasks=p.members.map((member,i)=>({id:'plan-'+i,title:i===0?'整理目标、规则与第一周计划':'整理资料并完成分工初稿',owner:member,due:'2026-09-12',done:false}));render();toast('已生成示例协作建议');},500);return;}
 }catch(error){toast(error.message);}
});
document.addEventListener('submit',event=>{
 const form=event.target;if(!['application-form','chat-form','profile-form','task-form','role-form'].includes(form.id))return;event.preventDefault();const data=new FormData(form);
 try{
 if(form.id==='application-form'){dispatchCollaboration({type:'apply',postId:form.dataset.postId,verified:user(actor).verified,fields:Object.fromEntries(data)});const a=demoStore.applications.at(-1);state.selectedApp=a.id;state.inbox='sent';goWorkspace('messages');toast('申请已提交（本地示例）');}
 if(form.id==='chat-form'){dispatchCollaboration({type:'message',appId:form.dataset.appId,text:data.get('message')});render();const feed=$('chat-feed');if(feed)feed.scrollTop=feed.scrollHeight;}
 if(form.id==='profile-form'){users[actor]={...user(actor),name:String(data.get('name')).trim(),major:String(data.get('major')).trim(),campus:String(data.get('campus')),hours:String(data.get('hours')).trim(),bio:String(data.get('bio')).trim(),skills:data.getAll('skills')};$('modal').close();render();toast('资料已保存到本次会话');}
 if(form.id==='task-form'){const team=demoStore.teams[state.teamId],old=team.tasks.find(t=>t.id===form.dataset.taskId);const values={title:String(data.get('title')).trim(),owner:String(data.get('owner')),due:String(data.get('due'))};if(!values.title)throw new Error('请填写任务标题');if(old)Object.assign(old,values);else team.tasks.push({id:'task-'+Date.now(),...values,done:false});$('modal').close();render();toast('任务已保存');}
 if(form.id==='role-form'){demoStore.teams[state.teamId].plan.roles.find(r=>r.user===form.dataset.userId).role=String(data.get('role')).trim();$('modal').close();render();toast('分工已更新');}
 }catch(error){if($('application-error'))$('application-error').textContent=error.message;else toast(error.message);}
});
document.addEventListener('change',event=>{const e=event.target;if(e.dataset.taskCheck){const p=demoStore.posts[state.teamId];if(p?.members.includes(actor)){demoStore.teams[state.teamId].tasks.find(t=>t.id===e.dataset.taskCheck).done=e.checked;render();}}if(e.dataset.preference){preferences[e.dataset.preference]=e.checked;persistDemo();}});
$('profile-shortcut').onclick=()=>goWorkspace('profile');$('notifications-button').onclick=()=>{state.inbox='notifications';goWorkspace('messages');};
$('demo-actor').onchange=e=>{actor=e.target.value;state.selectedApp=null;state.planError=null;if(!user(actor).verified&&['messages','teams','team'].includes(state.view))state.view='profile';if($('modal').open)$('modal').close();render();};
$('demo-ai-failure').onchange=e=>{state.aiFailure=e.target.checked;render();};
$('reset-demo').onclick=()=>showModal('重置示例',`<p>将清除这份草图本次会话中的申请、任务修改与关注，恢复预置示例。不会影响真实项目数据。</p><div class="form-actions"><button type="button" class="button" data-close-dialog>取消</button><button type="button" class="button primary" id="confirm-reset-demo">恢复示例</button></div>`);
document.addEventListener('click',e=>{if(e.target.closest('#confirm-reset-demo')){if(typeof resetPublishingDemo==='function')resetPublishingDemo();demoStore=seedCollaboration();users=structuredClone(initialUsers);actor='pei';state.followed=new Set();preferences={deadline:true,updates:true};readNotices=[];state.view='browse';state.channel='official';state.filters={official:freshFilter(),organization:freshFilter(),casual:freshFilter()};state.aiFailure=false;state.selectedApp=null;state.teamId=null;$('modal').close();render();}});
